version: '3.9'

services:
  registry:
    image: registry:2.8.2
    container_name: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: "yes"
    volumes:
      - /data/data/registry:/data
    restart: always
    networks:
      - default
networks:
  default:
    external:
      name: siwon-infra
    

  #nginx:
    #image: "nginx:1.9"
  #  container_name: registry_nginx
  #  build: ./nginx
  #  ports:
  #    - 5445:445
  #  links:
  #    - registry:registry
  #  volumes:
  #    - ./nginx/conf.d:/etc/nginx/conf.d
  #    - ./log/:/var/log/nginx
  #  restart: always
  #  extra_hosts:
  #      - "localhost:host-gateway"
  #  secrets:
  #    - source: ssl_sjwcorp_com_crt.pem
  #    - source: ssl_sjwcorp_com_key.pem

#secrets:
#  ssl_sjwcorp_com_crt.pem:
#    file: ./secrets/ssl/star_sjwcorp_kr_NginX_cert.pem
#  ssl_sjwcorp_com_key.pem:
#    file: ./secrets/ssl/star_sjwcorp_kr_NginX_key.pem
